# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tbc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='profile',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='tbc.Profile'),
        ),
    ]
