# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 16:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='category',
        ),
        migrations.RemoveField(
            model_name='ad',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='ad',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
