# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tbc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AlterField(
            model_name='lendandsell',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='LendAndSell_images'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='Projects_images'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(default='default_profile.jpg', upload_to='Service_images'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
