# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbc', '0003_auto_20190319_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='activities',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='reviews',
        ),
        migrations.DeleteModel(
            name='Inbox',
        ),
    ]
