# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-03 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tbc', '0002_auto_20190226_1729'),
        ('tbc', '0006_projects'),
    ]

    operations = [
    ]
